// GENERATED by src/challenges/__tests__/repsTable.test.ts — do not edit by hand.
// Regenerate after changing the corpus, a Reps kind or a lesson's reps spec:
//   REPS_TABLE_WRITE=1 npx vitest run src/challenges/__tests__/repsTable.test.ts
// Per lesson: the corpus files (by name, in order) a Reps run may draw on, and its edit range.
// Computing this live costs up to ~0.5 s per lesson (8 probe seeds x every file), so the first
// Reps or Warm-up open would block the main thread; the test above keeps it in sync.
export type RepsFit = { files: string[]; edits: [number, number] };

export const REPS_TABLE: Record<string, RepsFit> = {
  "change-words": { files: ["lcs.ts","quick_select.ts","stack.ts","query.ts","version1.go","kmp.go","util.go","version.lua","permissions.lua","minicyan.lua"], edits: [10, 15] },
  "intro-operators": { files: ["lcs.ts","quick_select.ts","stack.ts","query.ts","version1.go","kmp.go","util.go","version.lua","permissions.lua","minicyan.lua"], edits: [10, 15] },
  "delete-words": { files: ["lcs.ts","quick_select.ts","stack.ts","query.ts","version1.go","kmp.go","util.go","version.lua","permissions.lua","minicyan.lua"], edits: [10, 15] },
  "delete-lines": { files: ["lcs.ts","quick_select.ts","stack.ts","query.ts","version1.go","kmp.go","util.go","version.lua","permissions.lua","minicyan.lua"], edits: [10, 15] },
  "repeat-last-change": { files: ["lcs.ts","stack.ts","query.ts","version1.go","kmp.go","util.go","version.lua","permissions.lua","minicyan.lua"], edits: [10, 15] },
  "counts-operators": { files: ["lcs.ts","quick_select.ts","stack.ts","query.ts","version1.go","kmp.go","util.go","version.lua","permissions.lua","minicyan.lua"], edits: [10, 15] },
  "word-objects": { files: ["lcs.ts","stack.ts","query.ts","version1.go","kmp.go","util.go","version.lua","permissions.lua","minicyan.lua"], edits: [10, 15] },
  "text-objects-quotes": { files: ["reps.lua"], edits: [10, 15] },
  "text-objects-parens": { files: ["reps.ts","reps.go"], edits: [10, 15] },
  "search-forward": { files: ["lcs.ts","stack.ts","query.ts","version1.go","kmp.go","util.go","version.lua","permissions.lua","minicyan.lua"], edits: [10, 15] },
  "word-under-cursor": { files: ["lcs.ts","stack.ts","query.ts","version1.go","kmp.go","util.go","version.lua","permissions.lua","minicyan.lua"], edits: [10, 15] },
  "argument-objects": { files: ["reps.ts","reps.go"], edits: [10, 15] },
  "indent-objects": { files: ["reps.ts","reps.go","reps.lua"], edits: [10, 15] },
  "function-class-objects": { files: ["reps.ts"], edits: [9, 11] },
};
