// CURRICULUM.md is generated from the lesson registry: `npm run curriculum`.
// (Run through vitest via src/lessons/__tests__/curriculum-doc.test.ts; the sections import JSX.)
import { SECTIONS, numberOf } from '../src/lessons';
import type { Section } from '../src/lessons/types';

const BANDS: Record<Section['band'], { title: string; blurb: string }> = {
  core: { title: 'Core', blurb: 'Survive, then learn the grammar: motions, operators, text objects, visual mode, search.' },
  repeat: { title: 'Repeat', blurb: 'Make one edit do the work of many: registers and macros (the dot command lives in First Operators).' },
  project: { title: 'Project', blurb: 'Move through a codebase, not a file: buffers, windows, jumps, quickfix, pickers, the explorer.' },
  patterns: { title: 'Patterns', blurb: 'Edit at scale: the command line, substitute, global commands, project replace.' },
  code: { title: 'Code', blurb: 'What a starter config adds: LSP, richer text objects, flash, surround, completion, git.' },
  challenges: { title: 'Challenges', blurb: 'Generated files with many edits at once; the Coach reviews your keys.' },
};

const kindLabel = (k: string) => (k === 'rounds' ? 'transform' : k);

const PREAMBLE = `# vimchi — Curriculum

<!-- generated by scripts/curriculum.ts (npm run curriculum); do not edit by hand -->

A browser Vim tutor, inspired by vim-hero's short-lesson format: many small lessons, each teaching
1–4 keys, grouped into short named sections, then the project, pattern and plugin skills that
separate a power user from a competent one.

## Pathway

The order follows what the interactive tutors (vim-hero, Vimified, VimVenture), the books (Practical
Vim, Learn Vim the Smart Way), Primeagen's Vim Fundamentals, the config-building series (typecraft,
TJ DeVries) and the starter configs (kickstart.nvim, LazyVim) agree on. A lesson stays if its keys
are in the shared kickstart/LazyVim bindings or at least two of those sources teach it. Plugin
lessons show the keys the starters share; asides name the alternatives.
`;

const SHAPE = `## Lesson shape

Every lesson matches the live app:

1. **Intro**: two short paragraphs on the idea.
2. **Key cards**: one card per key, with a glyph and a label.
3. **Practice**: exactly one challenge.
4. **Results**: time, personal best, score, and Speed / Accuracy / Correct rings.
5. **Aside**: one short \`#\` note (a tip, a gotcha, or a Vim-vs-Neovim difference).

Sections may end with an optional **★ Boss**: a realistic multi-step edit with a par. Bosses and
Challenges don't count toward completion.

### Challenge types

| Type | Goal |
|---|---|
| \`target\` | reach randomly placed boxes |
| \`word\` | reach boxes on word starts/ends |
| \`fix\` | delete marked stray characters |
| \`replace\` | replace marked wrong characters |
| \`transform\` | make the buffer match a shown target text (diff highlighted); also multi-file and simulated-UI rounds graded on end state |
| \`quiz\` | type the keys for a described action; no buffer |
| \`generated\` | fix a seeded, mutated corpus file; live checklist |

Chips use Vim notation: \`C-d\` = Ctrl-d, \`␣\` = Space (the leader).
`;

const COACH = `## Coach

After a rounds lesson or a challenge run, "Better ways" lists up to five places where a
shorter sequence would have done the same edit, derived from the learner's own keys
(\`src/coach/\`): motion runs are searched for shorter routes (counts on hjkl, f/t/;, 0/^/$,
word motions, /search) and edits are matched against a rule library (\`3x\`, \`r\`, \`A\`, \`I\`,
\`ddp\`, \`.\`, \`cw\`, \`o\`). Suggestions use only keys taught at or before the lesson (counts from
\`words\`), must save ≥ 2 keys (or 1.5× on runs of 4+), never replace a key the lesson's section
drills, and are replay-verified on the engine including any register / find / search state a
later key reads. "Live hints" (sidebar footer, off by default) shows one such line under the
editor as you type. Every reference solution yields zero critiques (tested).
`;

export function renderCurriculum(): string {
  const out: string[] = [PREAMBLE];
  for (const b of Object.values(BANDS)) out.push(`- **${b.title}** — ${b.blurb}`);
  out.push('', SHAPE, '---', '');
  let band: Section['band'] | '' = '';
  for (const s of SECTIONS) {
    if (s.band !== band) {
      band = s.band;
      out.push(`## ${BANDS[band].title}`, '', BANDS[band].blurb, '');
    }
    out.push(`### ${s.title}`, '| # | Lesson | Keys | Challenge |', '|---|---|---|---|');
    for (const l of s.lessons) {
      const n = l.boss ? '★' : numberOf(l.id);
      out.push(`| ${n} | ${l.title} | ${l.chips.map(c => `\`${c}\``).join(' ')} | ${kindLabel(l.challenge.kind)} |`);
    }
    out.push('');
  }
  out.push(COACH, '## Size', '', '| Band | Sections | Lessons | Counted |', '|---|---|---|---|');
  let sections = 0, lessons = 0, counted = 0;
  for (const [id, b] of Object.entries(BANDS)) {
    const ss = SECTIONS.filter(s => s.band === id);
    const ls = ss.flatMap(s => s.lessons);
    const cs = ls.filter(l => !l.boss);
    sections += ss.length; lessons += ls.length; counted += cs.length;
    out.push(`| ${b.title} | ${ss.length} | ${ls.length} | ${cs.length} |`);
  }
  out.push(`| **Total** | **${sections}** | **${lessons}** | **${counted}** |`, '');
  return out.join('\n');
}
